# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DualProfileViewer
                                 A QGIS plugin
 Archaeological dual profile analysis with vector export
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2024
        email                : your.email@example.com
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QToolBar
from qgis.core import QgsProject
import os.path

# Import the main dialog
from .dual_profile_tool import ProfileViewerDialog
from .stratigraph_3d_dialog import Stratigraph3DDialog
from .stratigraph_integration import StratigraphIntegration

class DualProfileViewer:
    """Main plugin implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        
        # Initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DualProfileViewer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = '&Dual Profile Viewer'
        self.toolbar = None
        self.dialog = None
        self.stratigraph_dialog = None
        self.stratigraph_integration = StratigraphIntegration()

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('DualProfileViewer', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            if self.toolbar is None:
                self.toolbar = self.iface.addToolBar('Dual Profile Viewer')
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        icon_path2 = os.path.join(self.plugin_dir, 'stratigraph_logo.png')
        
        self.add_action(
            icon_path,
            text=self.tr('Dual Profile Viewer'),
            callback=self.run,
            parent=self.iface.mainWindow(),
            status_tip=self.tr('Create dual elevation profiles from DEM/DTM'),
            whats_this=self.tr('Archaeological dual profile analysis tool'))
        
        # Add 3D visualization action
        self.add_action(
            icon_path2,
            text=self.tr('3D Stratigraphic Visualization'),
            callback=self.run_3d_visualization,
            parent=self.iface.mainWindow(),
            status_tip=self.tr('Create 3D stratigraphic visualizations'),
            whats_this=self.tr('3D visualization using stratigraph library'))

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.menu,
                action)
            self.iface.removeToolBarIcon(action)
        
        if self.toolbar:
            del self.toolbar

    def run(self):
        """Run method that performs all the real work"""
        # Create dialog if it doesn't exist
        if not self.dialog:
            self.dialog = ProfileViewerDialog(self.iface, parent=self.iface.mainWindow())
        
        # Show the dialog
        self.dialog.show()
        # Run the dialog event loop
        result = self.dialog.exec_()
    
    def run_3d_visualization(self):
        """Open the 3D stratigraphic visualization dialog"""
        if not self.stratigraph_dialog:
            self.stratigraph_dialog = Stratigraph3DDialog(parent=self.iface.mainWindow())
            self.stratigraph_dialog.visualization_requested.connect(self.create_3d_visualization)
        
        self.stratigraph_dialog.show()
        self.stratigraph_dialog.exec_()
    
    def create_3d_visualization(self, settings):
        """Create 3D visualization with the given settings"""
        from qgis.core import QgsMessageLog, Qgis
        
        QgsMessageLog.logMessage("Starting 3D visualization", "DualProfileViewer", Qgis.Info)
        
        # Check if we have profile data from the main dialog
        if self.dialog and hasattr(self.dialog, 'get_profile_data'):
            profile_data = self.dialog.get_profile_data()
            QgsMessageLog.logMessage(f"Got profile data: {type(profile_data)}, length: {len(profile_data) if profile_data else 0}", "DualProfileViewer", Qgis.Info)
            
            # Check if we have multiple profiles for cross-sections
            profile_data_list = []
            if hasattr(self.dialog, 'get_all_profile_data'):
                profile_data_list = self.dialog.get_all_profile_data()
            elif profile_data:
                profile_data_list = [profile_data]
                
            if profile_data_list:
                # Load the first profile for basic operations
                self.stratigraph_integration.load_profile_data(profile_data_list[0])
                self.stratigraph_integration.create_stratigraphic_model(
                    layer_boundaries=None  # Auto-generate based on settings
                )
                # Pass all profiles for cross-section visualization
                self.stratigraph_integration.visualize_3d(
                    show_layers=settings['show_layers'],
                    exploded=settings['exploded_view'],
                    settings=settings,
                    profile_data_list=profile_data_list
                )
            else:
                from PyQt5.QtWidgets import QMessageBox
                QMessageBox.warning(None, "No Data", "Please create profiles first before 3D visualization")
